### ISSUE TITLE
Typescript compilations errors

### ISSUE THREAD

**Issue by alexilyaev** [500tech/shredderjs#14]
It fails when trying to load `uuid` module.

```
ERROR in /Users/alex/Web Dev/Node/shredderjs/lib/api/models/rule.ts
(2,18): error TS2307: Cannot find module 'uuid'.
```

Ref:
https://github.com/Microsoft/TypeScript/issues/2709

Also, `Object.assign` does not work in IE, so we should polyfill it, though I'm not sure how to get Typescript to eat that.
https://github.com/Microsoft/TypeScript/issues/3889

**Comment by morsdyce** [comment]
Closed as we decided not to continue with typescript.
