### ISSUE TITLE
Things not covered by design document

### ISSUE THREAD

**Issue by ilyagelman** [500tech/shredderjs#4]
* Request/response headers
* Parameters (query/form-data)

**Comment by alexilyaev** [comment]
Can you elaborate on these 2 with expected behavior?

**Comment by morsdyce** [comment]
I've added response headers to the mock rule properties, as shredder is meant to be the server we should not deal with request headers as they are supposed to come as is from the application making the request.

Regarding parameters, it might be nice to have route matching according to parameters being sent however that is an advanced feature which I think isn't necessary for the initial version.

In addition another thing we could do with parameters is transform mocked responses into a small template language where it allows you to use parameters you received in the request to use in the response.
