### ISSUE TITLE
Create XMLHttpRequest Capturing polyfill

### ISSUE THREAD

**Issue by morsdyce** [500tech/shredderjs#5]

**Comment by alexilyaev** [comment]
Why Polyfill? I think that this would work if it's loaded before Angular (or whatever library):
http://stackoverflow.com/questions/629671/how-can-i-intercept-xmlhttprequests-from-a-greasemonkey-script

**Comment by morsdyce** [comment]
Because we need to modify the response, we don't need to polyfill the entire API, just the parts we need.

@ilyagelman is currently investigating this

**Comment by ilyagelman** [comment]
So I found this package: https://github.com/jpillora/xhook

```
xhook.before((request) => {
  if (request.url.match('/users')) {
    return { status: 200, data: { a: 1 } }
  }
});
```

It also has can be easily disabled with ```xhook.disable()```

It does not support fetch() though, but we can use it for v1 just to make things up and running.
